### ISSUE TITLE
Compatibility with MkDocs 1.5 and Markdown 3.4.4 a

### ISSUE THREAD

**Issue by BelovaIrina22** [iSOLveIT/mkdocs-pdf-generate#20]
On July 26, a new MkDocs version was published - version 1.5 (https://www.mkdocs.org/about/release-notes/#version-150-2023-07-26). This is a major update and there have been a lot of changes, one of the changes is the Markdown version.
It seems that MkDocs 1.5 and Markdown 3.4.4 are not compatible with the current version of the mkdocs-pdf-generate plugin.
With MkDocs 1.4.3, Markdown 3.3.7 everything works fine.

**Comment by iSOLveIT** [comment]
Thanks for raising the issue. I will check it out.

**Comment by iSOLveIT** [comment]
Issue solved by PR #21.
